# import = ["/home/luis/.config/alacritty/themes/Everforest-Dark-Hard.toml"]

[cursor]
blink_interval = 400
blink_timeout = 0

[cursor.style]
blinking = "always"
shape = "Block"

[font]
size = 11.0

[font.bold]
family = "terminus"
style = "Bold"

[font.normal]
family = "terminus"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 6
y = 4


[colors.primary]
background= "#272e33"
foreground= "#d3c6aa"

[colors.cursor]
text= "#272e33"
cursor= "#d3c6aa"

[colors.normal]
black=   "#414b50"
red=     "#e67e80"
green=   "#a7c080"
yellow=  "#dbbc7f"
blue=    "#7fbbb3"
magenta= "#d699b6"
cyan=    "#83c092"
white=   "#d3c6aa"

[colors.bright]
black=   "#475258"
red=     "#e67e80"
green=   "#a7c080"
yellow=  "#dbbc7f"
blue=    "#7fbbb3"
magenta= "#d699b6"
cyan=    "#83c092"
white=   "#d3c6aa"
